version: "3"
services:
  angie:
    image: docker.angie.software/angie:1.3.1-alpine
    volumes:
      - ./angie.conf:/etc/angie/angie.conf
      - ./default.conf:/etc/angie/http.d/default.conf
      - ./videos:/opt/static/videos/
      - ./index.html:/usr/share/angie/html/index.html
      - ./hls.js:/usr/share/angie/html/hls.js
    ports:
      - "80:80"
      - "443:443"
     